create database Ahitofel_EY_240821
go
------------
use database Ahitofel_EY_240821
go
/*
Deployment script for Ahitofel_EY_240821

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Ahitofel_EY_240821"
:setvar DefaultFilePrefix "Ahitofel_EY_240821"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Black_list]...';


GO
CREATE TABLE [dbo].[Black_list] (
    [Customer_id] INT  NOT NULL,
    [Entery_date] DATE NOT NULL,
    [End_date]    DATE NULL,
    CONSTRAINT [PK_Black_list] PRIMARY KEY CLUSTERED ([Customer_id] ASC, [Entery_date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Childrends]...';


GO
CREATE TABLE [dbo].[Childrends] (
    [Yoetz_ID]   INT          NULL,
    [Child_ID]   INT          NOT NULL,
    [Name]       VARCHAR (10) NULL,
    [Last_name]  VARCHAR (10) NULL,
    [Birth_Date] DATE         NULL,
    [Country]    VARCHAR (10) NULL,
    [City_Name]  VARCHAR (10) NULL,
    [Zip_Code]   INT          NULL,
    CONSTRAINT [PK_Childrends] PRIMARY KEY CLUSTERED ([Child_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [Customer_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [Customer_Name] VARCHAR (10) NOT NULL,
    [Foreign_Ind]   VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([Customer_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Customers_Adderss]...';


GO
CREATE TABLE [dbo].[Customers_Adderss] (
    [Customer_ID]            INT          NOT NULL,
    [Country]                VARCHAR (10) NOT NULL,
    [Address_ID]             VARCHAR (20) NOT NULL,
    [City_Name]              VARCHAR (10) NOT NULL,
    [Zip_Code]               INT          NULL,
    [DISTANCE_From_Ahitofel] FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_Customers_Adderss] PRIMARY KEY CLUSTERED ([Customer_ID] ASC, [Address_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Extra_Credit]...';


GO
CREATE TABLE [dbo].[Extra_Credit] (
    [Credit_Code]   INT          NOT NULL,
    [Credit_Name]   VARCHAR (10) NULL,
    [Credit_Points] FLOAT (53)   NULL,
    [Entry_Date]    DATETIME     NULL,
    [Delete_Date]   DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([Credit_Code] ASC)
);


GO
PRINT N'Creating Table [dbo].[Family_OF_Managers_Center]...';


GO
CREATE TABLE [dbo].[Family_OF_Managers_Center] (
    [Manager_ID]         INT          NOT NULL,
    [Spouse_OR_Child_ID] INT          NOT NULL,
    [Spouse_OR_Child]    BIT          NULL,
    [First_Name]         VARCHAR (10) NULL,
    [Last_Name]          VARCHAR (10) NULL,
    [BirthDate]          DATE         NULL,
    [Favorite_Cake]      VARCHAR (10) NULL,
    [Cake_Voucher]       VARCHAR (10) NULL,
    [Country]            NCHAR (10)   NULL,
    [City_Name]          NCHAR (10)   NULL,
    [Zip]                INT          NULL,
    CONSTRAINT [PK_Family_OF_Managers_Center] PRIMARY KEY CLUSTERED ([Spouse_OR_Child_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Frauds]...';


GO
CREATE TABLE [dbo].[Frauds] (
    [Yoetz_id]         INT           NOT NULL,
    [Yoetz_ManagerId]  INT           NULL,
    [Entry_Date]       DATETIME      NOT NULL,
    [Appointment_date] DATE          NULL,
    [Fraud_YN]         VARCHAR (3)   NULL,
    [result_text]      VARCHAR (MAX) NULL,
    [Delete_Date]      DATETIME      NULL,
    CONSTRAINT [PK_Frauds] PRIMARY KEY CLUSTERED ([Yoetz_id] ASC, [Entry_Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Hagim]...';


GO
CREATE TABLE [dbo].[Hagim] (
    [TDate] DATETIME       NOT NULL,
    [Code]  INT            NULL,
    [Name]  NVARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([TDate] ASC)
);


GO
PRINT N'Creating Table [dbo].[Hearing_at_HR]...';


GO
CREATE TABLE [dbo].[Hearing_at_HR] (
    [Yoetz_ID]       INT           NOT NULL,
    [HR_employee_id] INT           NULL,
    [Warning_id]     TINYINT       NULL,
    [HR_Date]        DATE          NOT NULL,
    [Deleted_Date]   DATE          NULL,
    [Yoetz_fired]    BIT           NULL,
    [Result_Text]    VARCHAR (MAX) NULL,
    [END_Date]       DATETIME      NULL,
    CONSTRAINT [PK_Hearing_at_HR] PRIMARY KEY CLUSTERED ([Yoetz_ID] ASC, [HR_Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Managers_Center]...';


GO
CREATE TABLE [dbo].[Managers_Center] (
    [Manager_ID]    INT          NOT NULL,
    [First_Name]    VARCHAR (10) NULL,
    [Last_Name]     VARCHAR (10) NULL,
    [Birth_Date]    DATE         NULL,
    [Favorite_Cake] VARCHAR (10) NULL,
    [Senior]        BIT          NULL,
    [ReportTo]      INT          NULL,
    [Country]       NCHAR (10)   NULL,
    [City_Name]     NCHAR (10)   NULL,
    [Zip]           INT          NULL,
    CONSTRAINT [PK_Managers_Center] PRIMARY KEY CLUSTERED ([Manager_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[MSSQL_TemporalHistoryFor_1829581556]...';


GO
CREATE TABLE [dbo].[MSSQL_TemporalHistoryFor_1829581556] (
    [Currency_Id]   FLOAT (53)    NOT NULL,
    [Curreny_name]  VARCHAR (10)  NULL,
    [Exchange_Rate] FLOAT (53)    NULL,
    [ValidFrom]     DATETIME2 (2) NOT NULL,
    [ValidTo]       DATETIME2 (2) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[MSSQL_TemporalHistoryFor_1829581556].[ix_MSSQL_TemporalHistoryFor_1829581556]...';


GO
CREATE CLUSTERED INDEX [ix_MSSQL_TemporalHistoryFor_1829581556]
    ON [dbo].[MSSQL_TemporalHistoryFor_1829581556]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[Payment_Percent]...';


GO
CREATE TABLE [dbo].[Payment_Percent] (
    [Code_Percent]  INT          NOT NULL,
    [Name_Percent]  VARCHAR (10) NULL,
    [Extra_Percent] FLOAT (53)   NULL,
    [Entry_Date]    DATE         NOT NULL,
    [Delete_Date]   DATE         NULL,
    CONSTRAINT [PK_Payment_Percent] PRIMARY KEY CLUSTERED ([Code_Percent] ASC, [Entry_Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Payment_System]...';


GO
CREATE TABLE [dbo].[Payment_System] (
    [Project_ID]                 INT           NOT NULL,
    [Payment_DueDate]            DATE          NOT NULL,
    [Vat]                        FLOAT (53)    NULL,
    [Price]                      FLOAT (53)    NULL,
    [Extra_Code_LOCKED]          INT           NULL,
    [Currency_ID]                FLOAT (53)    NULL,
    [Curency_Date]               DATETIME2 (2) NULL,
    [Code_Payment_Percent]       INT           NULL,
    [PaymentCurrency_Entry_date] DATE          NULL,
    [InvoicePayDate]             DATE          NULL,
    CONSTRAINT [PK_Payment_System_1] PRIMARY KEY CLUSTERED ([Project_ID] ASC, [Payment_DueDate] ASC)
);


GO
PRINT N'Creating Table [dbo].[Projects]...';


GO
CREATE TABLE [dbo].[Projects] (
    [Project_ID]        INT          IDENTITY (1, 1) NOT NULL,
    [Customer_ID]       INT          NOT NULL,
    [Address_ID]        VARCHAR (20) NULL,
    [Project_Cost]      INT          NOT NULL,
    [BlackList]         BIT          NULL,
    [Locked]            VARCHAR (10) NULL,
    [Manager_Center_ID] INT          NULL,
    PRIMARY KEY CLUSTERED ([Project_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Salary]...';


GO
CREATE TABLE [dbo].[Salary] (
    [Yoetz_ID]             INT        NOT NULL,
    [Credit_Code]          INT        NULL,
    [Basic_Wage]           FLOAT (53) NULL,
    [Socialy_Add]          FLOAT (53) NULL,
    [Extra_Wage]           FLOAT (53) NULL,
    [Project_Manager]      BIT        NULL,
    [Entry_Date]           DATETIME   NOT NULL,
    [Delete_Date]          DATETIME   NULL,
    [Code_Payment_Percent] INT        NULL,
    [Payment_Entry_date]   DATE       NULL,
    CONSTRAINT [PK_Salary] PRIMARY KEY CLUSTERED ([Yoetz_ID] ASC, [Entry_Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Spouses]...';


GO
CREATE TABLE [dbo].[Spouses] (
    [Yoetz_ID]   INT          NULL,
    [Spous_ID]   INT          NOT NULL,
    [First_Name] VARCHAR (10) NULL,
    [Last_Name]  VARCHAR (10) NULL,
    [Country]    VARCHAR (10) NULL,
    [City_Name]  VARCHAR (10) NULL,
    [Zip_Code]   INT          NULL,
    CONSTRAINT [PK_Spouses] PRIMARY KEY CLUSTERED ([Spous_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[System_Work_Hours]...';


GO
CREATE TABLE [dbo].[System_Work_Hours] (
    [Project_ID] INT      NOT NULL,
    [Yoetz_ID]   INT      NOT NULL,
    [Entry_Date] DATE     NOT NULL,
    [Entry_Hour] TIME (7) NULL,
    [End_Hour]   TIME (7) NULL,
    [DIffTeam]   BIT      NULL,
    CONSTRAINT [PK_System_Work_Hours] PRIMARY KEY CLUSTERED ([Project_ID] ASC, [Yoetz_ID] ASC, [Entry_Date] ASC)
);


GO
PRINT N'Creating Table [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [Team_ID]    INT          NOT NULL,
    [Project_ID] INT          NOT NULL,
    [Team_Name]  VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([Team_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Yoatzim]...';


GO
CREATE TABLE [dbo].[Yoatzim] (
    [Yoetz_ID]       INT          IDENTITY (1, 1) NOT NULL,
    [Firstname]      VARCHAR (10) NOT NULL,
    [Lastname]       VARCHAR (10) NOT NULL,
    [Sex]            VARCHAR (10) NULL,
    [Marital_Status] VARCHAR (10) NULL,
    [StartDate]      DATE         NULL,
    [EndDate]        DATE         NULL,
    CONSTRAINT [PK__Yoatzim__9A62671D8000C1B6] PRIMARY KEY CLUSTERED ([Yoetz_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Yoatzim_Address]...';


GO
CREATE TABLE [dbo].[Yoatzim_Address] (
    [Yoetz_ID]   INT          NOT NULL,
    [Country]    VARCHAR (10) NOT NULL,
    [Address_ID] VARCHAR (20) NOT NULL,
    [City_Name]  VARCHAR (10) NOT NULL,
    [Zip_Code]   INT          NULL,
    CONSTRAINT [PK_Yoatzim_Address] PRIMARY KEY CLUSTERED ([Yoetz_ID] ASC, [Address_ID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Yoetz_Teams]...';


GO
CREATE TABLE [dbo].[Yoetz_Teams] (
    [Team_Id]      INT NOT NULL,
    [Yoetz_Id]     INT NOT NULL,
    [Team_manager] BIT NULL,
    CONSTRAINT [PK_Yoetz_Teams] PRIMARY KEY CLUSTERED ([Team_Id] ASC, [Yoetz_Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Exchange_Rate]...';


GO
CREATE TABLE [dbo].[Exchange_Rate] (
    [Currency_Id]   FLOAT (53)                                       NOT NULL,
    [Curreny_name]  VARCHAR (10)                                     NULL,
    [Exchange_Rate] FLOAT (53)                                       NULL,
    [ValidFrom]     DATETIME2 (2) GENERATED ALWAYS AS ROW START      NOT NULL,
    [ValidTo]       DATETIME2 (2) GENERATED ALWAYS AS ROW END HIDDEN NOT NULL,
    PRIMARY KEY CLUSTERED ([Currency_Id] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[MSSQL_TemporalHistoryFor_1829581556], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Default Constraint [dbo].[DF__Hearing_a__HR_Da__52593CB8]...';


GO
ALTER TABLE [dbo].[Hearing_at_HR]
    ADD CONSTRAINT [DF__Hearing_a__HR_Da__52593CB8] DEFAULT (getdate()) FOR [HR_Date];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Black_list_Customers]...';


GO
ALTER TABLE [dbo].[Black_list] WITH NOCHECK
    ADD CONSTRAINT [FK_Black_list_Customers] FOREIGN KEY ([Customer_id]) REFERENCES [dbo].[Customers] ([Customer_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Childrends_Yoatzim]...';


GO
ALTER TABLE [dbo].[Childrends] WITH NOCHECK
    ADD CONSTRAINT [FK_Childrends_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Customers_Adderss_Customers]...';


GO
ALTER TABLE [dbo].[Customers_Adderss] WITH NOCHECK
    ADD CONSTRAINT [FK_Customers_Adderss_Customers] FOREIGN KEY ([Customer_ID]) REFERENCES [dbo].[Customers] ([Customer_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Family_OF_Managers_Center_Managers_Center]...';


GO
ALTER TABLE [dbo].[Family_OF_Managers_Center] WITH NOCHECK
    ADD CONSTRAINT [FK_Family_OF_Managers_Center_Managers_Center] FOREIGN KEY ([Manager_ID]) REFERENCES [dbo].[Managers_Center] ([Manager_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Frauds_Yoatzim]...';


GO
ALTER TABLE [dbo].[Frauds] WITH NOCHECK
    ADD CONSTRAINT [FK_Frauds_Yoatzim] FOREIGN KEY ([Yoetz_id]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Hearing_at_HR_Yoatzim]...';


GO
ALTER TABLE [dbo].[Hearing_at_HR] WITH NOCHECK
    ADD CONSTRAINT [FK_Hearing_at_HR_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Payment_System_Exchange_Rate]...';


GO
ALTER TABLE [dbo].[Payment_System] WITH NOCHECK
    ADD CONSTRAINT [FK_Payment_System_Exchange_Rate] FOREIGN KEY ([Currency_ID]) REFERENCES [dbo].[Exchange_Rate] ([Currency_Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Payment_System_Payment_Percent]...';


GO
ALTER TABLE [dbo].[Payment_System] WITH NOCHECK
    ADD CONSTRAINT [FK_Payment_System_Payment_Percent] FOREIGN KEY ([Code_Payment_Percent], [PaymentCurrency_Entry_date]) REFERENCES [dbo].[Payment_Percent] ([Code_Percent], [Entry_Date]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Payment_System_Projects]...';


GO
ALTER TABLE [dbo].[Payment_System] WITH NOCHECK
    ADD CONSTRAINT [FK_Payment_System_Projects] FOREIGN KEY ([Project_ID]) REFERENCES [dbo].[Projects] ([Project_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Customers]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Customers] FOREIGN KEY ([Customer_ID]) REFERENCES [dbo].[Customers] ([Customer_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Managers_Center]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Managers_Center] FOREIGN KEY ([Manager_Center_ID]) REFERENCES [dbo].[Managers_Center] ([Manager_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salary_Extra_Credit]...';


GO
ALTER TABLE [dbo].[Salary] WITH NOCHECK
    ADD CONSTRAINT [FK_Salary_Extra_Credit] FOREIGN KEY ([Credit_Code]) REFERENCES [dbo].[Extra_Credit] ([Credit_Code]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salary_Hagim]...';


GO
ALTER TABLE [dbo].[Salary] WITH NOCHECK
    ADD CONSTRAINT [FK_Salary_Hagim] FOREIGN KEY ([Entry_Date]) REFERENCES [dbo].[Hagim] ([TDate]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salary_Payment_Percent]...';


GO
ALTER TABLE [dbo].[Salary] WITH NOCHECK
    ADD CONSTRAINT [FK_Salary_Payment_Percent] FOREIGN KEY ([Code_Payment_Percent], [Payment_Entry_date]) REFERENCES [dbo].[Payment_Percent] ([Code_Percent], [Entry_Date]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Salary_Yoatzim]...';


GO
ALTER TABLE [dbo].[Salary] WITH NOCHECK
    ADD CONSTRAINT [FK_Salary_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Spouses_Yoatzim]...';


GO
ALTER TABLE [dbo].[Spouses] WITH NOCHECK
    ADD CONSTRAINT [FK_Spouses_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_System_Work_Hours_Projects]...';


GO
ALTER TABLE [dbo].[System_Work_Hours] WITH NOCHECK
    ADD CONSTRAINT [FK_System_Work_Hours_Projects] FOREIGN KEY ([Project_ID]) REFERENCES [dbo].[Projects] ([Project_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_System_Work_Hours_Yoatzim]...';


GO
ALTER TABLE [dbo].[System_Work_Hours] WITH NOCHECK
    ADD CONSTRAINT [FK_System_Work_Hours_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Teams_Projects]...';


GO
ALTER TABLE [dbo].[Teams] WITH NOCHECK
    ADD CONSTRAINT [FK_Teams_Projects] FOREIGN KEY ([Project_ID]) REFERENCES [dbo].[Projects] ([Project_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Yoatzim_Address_Yoatzim]...';


GO
ALTER TABLE [dbo].[Yoatzim_Address] WITH NOCHECK
    ADD CONSTRAINT [FK_Yoatzim_Address_Yoatzim] FOREIGN KEY ([Yoetz_ID]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Yoetz_Teams_Teams]...';


GO
ALTER TABLE [dbo].[Yoetz_Teams] WITH NOCHECK
    ADD CONSTRAINT [FK_Yoetz_Teams_Teams] FOREIGN KEY ([Team_Id]) REFERENCES [dbo].[Teams] ([Team_ID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Yoetz_Teams_Yoatzim]...';


GO
ALTER TABLE [dbo].[Yoetz_Teams] WITH NOCHECK
    ADD CONSTRAINT [FK_Yoetz_Teams_Yoatzim] FOREIGN KEY ([Yoetz_Id]) REFERENCES [dbo].[Yoatzim] ([Yoetz_ID]);


GO
PRINT N'Creating Check Constraint [dbo].[CONS_AGE]...';


GO
ALTER TABLE [dbo].[Family_OF_Managers_Center] WITH NOCHECK
    ADD CONSTRAINT [CONS_AGE] CHECK ((datediff(year,[BirthDate],getdate())-case when (datepart(month,[BirthDate])*(100)+datepart(day,[BirthDate]))>(datepart(month,getdate())*(100)+datepart(day,getdate())) then (1) else (0) end)<(18));


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Black_list] WITH CHECK CHECK CONSTRAINT [FK_Black_list_Customers];

ALTER TABLE [dbo].[Childrends] WITH CHECK CHECK CONSTRAINT [FK_Childrends_Yoatzim];

ALTER TABLE [dbo].[Customers_Adderss] WITH CHECK CHECK CONSTRAINT [FK_Customers_Adderss_Customers];

ALTER TABLE [dbo].[Family_OF_Managers_Center] WITH CHECK CHECK CONSTRAINT [FK_Family_OF_Managers_Center_Managers_Center];

ALTER TABLE [dbo].[Frauds] WITH CHECK CHECK CONSTRAINT [FK_Frauds_Yoatzim];

ALTER TABLE [dbo].[Hearing_at_HR] WITH CHECK CHECK CONSTRAINT [FK_Hearing_at_HR_Yoatzim];

ALTER TABLE [dbo].[Payment_System] WITH CHECK CHECK CONSTRAINT [FK_Payment_System_Exchange_Rate];

ALTER TABLE [dbo].[Payment_System] WITH CHECK CHECK CONSTRAINT [FK_Payment_System_Payment_Percent];

ALTER TABLE [dbo].[Payment_System] WITH CHECK CHECK CONSTRAINT [FK_Payment_System_Projects];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Customers];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Managers_Center];

ALTER TABLE [dbo].[Salary] WITH CHECK CHECK CONSTRAINT [FK_Salary_Extra_Credit];

ALTER TABLE [dbo].[Salary] WITH CHECK CHECK CONSTRAINT [FK_Salary_Hagim];

ALTER TABLE [dbo].[Salary] WITH CHECK CHECK CONSTRAINT [FK_Salary_Payment_Percent];

ALTER TABLE [dbo].[Salary] WITH CHECK CHECK CONSTRAINT [FK_Salary_Yoatzim];

ALTER TABLE [dbo].[Spouses] WITH CHECK CHECK CONSTRAINT [FK_Spouses_Yoatzim];

ALTER TABLE [dbo].[System_Work_Hours] WITH CHECK CHECK CONSTRAINT [FK_System_Work_Hours_Projects];

ALTER TABLE [dbo].[System_Work_Hours] WITH CHECK CHECK CONSTRAINT [FK_System_Work_Hours_Yoatzim];

ALTER TABLE [dbo].[Teams] WITH CHECK CHECK CONSTRAINT [FK_Teams_Projects];

ALTER TABLE [dbo].[Yoatzim_Address] WITH CHECK CHECK CONSTRAINT [FK_Yoatzim_Address_Yoatzim];

ALTER TABLE [dbo].[Yoetz_Teams] WITH CHECK CHECK CONSTRAINT [FK_Yoetz_Teams_Teams];

ALTER TABLE [dbo].[Yoetz_Teams] WITH CHECK CHECK CONSTRAINT [FK_Yoetz_Teams_Yoatzim];

ALTER TABLE [dbo].[Family_OF_Managers_Center] WITH CHECK CHECK CONSTRAINT [CONS_AGE];


GO
PRINT N'Update complete.';


GO
